// docs/src/components/react/ButtonExample.jsx
export default function ButtonExample() {
  return (
    <div className="docs-demo-row">
      <button className="corn-button">React Primary</button>
      <button className="corn-button corn-button--secondary">React Secondary</button>
      <button className="corn-button corn-button--danger">React Danger</button>
    </div>
  );
}

// docs/src/components/vue/ButtonExample.vue
<template>
  <div class="docs-demo-row">
    <button class="corn-button" type="button">Vue Primary</button>
    <button class="corn-button corn-button--secondary" type="button">Vue Secondary</button>
    <button class="corn-button corn-button--danger" type="button">Vue Danger</button>
  </div>
</template>
